id: I5C7201F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:30:50+00:00'
last_modified: '2022-06-08T11:08:06.043196+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC382
  title: 'མཁས་གྲུབ་ཀརྨ་ཆགས་མེད་ཀྱི་རྣམ་ཐར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DDDD:
      image_group_id: I2PD18230
      title: ''
      total_pages: 432
      order: 1
      base_file: DDDD.txt
    '2832':
      image_group_id: I2PD18231
      title: ''
      total_pages: 434
      order: 2
      base_file: 2832.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
